---
# =============================================================================
# Production Environment
# =============================================================================

deploy_profile: production

env_overrides:
  PRODUCTION: "true"
  DB_BIND_ADDRESS: "127.0.0.1:"
